/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be in your git repository.
// It is generated by the Expo CLI automatically. See:
// https://docs.expo.dev/guides/typescript/#exposing-types-for-expo-router
